# Generated by Django 5.2.17 on 2026-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('language', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
